name: Trigger auto deployment for container-app-ulw4lo5avgfwu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-ulw4lo5avgfwu-AutoDeployTrigger-372d2ec6-b1d0-4d43-bb07-d5a96d6ab6a6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPULW4LO5AVGFWU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPULW4LO5AVGFWU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPULW4LO5AVGFWU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPULW4LO5AVGFWU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPULW4LO5AVGFWU_REGISTRY_PASSWORD }}
          containerAppName: container-app-ulw4lo5avgfwu
          resourceGroup: expresssample8508b614
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


